import 'package:hive/hive.dart';

part 'habit.g.dart'; // This file will be generated by build_runner

@HiveType(typeId: 1)
class HabitFrequency extends HiveObject {
  @HiveField(0)
  final String type; // 'daily' or 'weekdays'

  @HiveField(1)
  final List<int> days; // e.g., [1, 2, 3, 4, 5] for Mon-Fri



  HabitFrequency({required this.type, required this.days});
}

@HiveType(typeId: 0)

class Habit extends HiveObject {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final String name;

  @HiveField(2)
  final String icon; // Emoji character

  @HiveField(3)
  final HabitFrequency frequency;

  @HiveField(4)
  final String? reminderTime; // Stored as "HH:mm", e.g., "08:30"

  @HiveField(5)
  final DateTime createdAt;

  @HiveField(6)
  final String? subtype;

  Habit({
    required this.id,
    required this.name,
    required this.icon,
    required this.frequency,
    this.reminderTime,
    required this.createdAt,
    this.subtype
  });
}